---
- name: Windows Test Playbook
  hosts: all

  tasks:
    - debug:
        msg: Below commands will run under ...
    - name: Example from an Ansible Playbook
      win_ping:

    - name: Induce an exception to see what happens
      win_ping:
data: crash
