# Test connectivity to a windows host
# ansible winserver -m win_ping

- hosts: all

- name: Example from an Ansible Playbook
  win_ping:

- name: Induce an exception to see what happens
  win_ping:
    data: crash
